# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "72c4faa9002303418815b5ac78bf3b27"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "cinegearpro-back-in-stock"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
